(function initializeCindraYouTubeContent(root) {
  'use strict';

  root.CindraYouTubeContent?.cleanup?.();
  const { CindraErrors: errors, CindraMessages: messages, CindraYouTubeUi: youtubeUi,
    CindraYouTubeParser: parser } = root;
  if (!errors || !messages || !youtubeUi || !parser) return;

  const ACTIONS = messages.ACTIONS;
  const PANEL_SELECTOR = 'ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"], ' +
    'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"], ' +
    'yt-section-list-renderer[data-target-id="PAmodern_transcript_view"]';
  let active = null;
  let transcriptButton;
  let cleanedUp = false;

  function currentVideoId() {
    return root.location.pathname === '/watch' ? new URLSearchParams(root.location.search).get('v') : null;
  }

  function failure(code, message) {
    return Object.assign(new Error(message), { code });
  }

  function assertCurrent(job) {
    if (job.controller.signal.aborted) throw job.controller.signal.reason;
    if (cleanedUp || currentVideoId() !== job.videoId) {
      throw failure('NAVIGATED', 'The YouTube video changed. Please summarize the current video again.');
    }
  }

  function delay(ms, job) {
    assertCurrent(job);
    return new Promise((resolve, reject) => {
      const signal = job.controller.signal;
      const abort = () => { clearTimeout(timer); reject(signal.reason); };
      const timer = setTimeout(() => { signal.removeEventListener('abort', abort); resolve(); }, ms);
      signal.addEventListener('abort', abort, { once: true });
    });
  }

  async function snapshot(job, includePanel = false) {
    assertCurrent(job);
    const response = await messages.runtimeSendMessage({
      action: ACTIONS.READ_YOUTUBE_PAGE, videoId: job.videoId, includePanel
    }, { context: 'read current YouTube player', timeoutMs: 2000 });
    assertCurrent(job);
    return response?.success && response.data?.videoId === job.videoId ? response.data : null;
  }

  async function fetchText(url, job, options = {}) {
    assertCurrent(job);
    const parsed = new URL(url);
    if (parsed.origin !== 'https://www.youtube.com' ||
        !['/watch', '/api/timedtext', '/youtubei/v1/get_transcript', '/youtubei/v1/get_panel'].includes(parsed.pathname)) {
      throw new Error('Unexpected YouTube transcript URL.');
    }
    if (parsed.searchParams.has('v') && parsed.searchParams.get('v') !== job.videoId) {
      throw new Error('Caption URL belongs to a different video.');
    }
    const controller = new AbortController();
    const abort = () => controller.abort(job.controller.signal.reason);
    job.controller.signal.addEventListener('abort', abort, { once: true });
    const timer = setTimeout(() => controller.abort(new Error('YouTube caption request timed out.')), 2500);
    try {
      const response = await fetch(url, {
        ...options, credentials: 'include', redirect: 'error', signal: controller.signal
      });
      if (!response.ok) throw new Error(`YouTube caption request failed (${response.status}).`);
      const text = await response.text();
      assertCurrent(job);
      if (text.length > 8000000) throw new Error('YouTube caption response was too large.');
      return text;
    } finally {
      clearTimeout(timer);
      job.controller.signal.removeEventListener('abort', abort);
    }
  }

  function result(job, player, segments, source, track = null) {
    assertCurrent(job);
    const transcript = parser.formatSegments(segments);
    if (!transcript) throw failure('EMPTY', 'YouTube returned an empty transcript.');
    const details = player?.videoDetails || {};
    return {
      success: true,
      videoId: job.videoId,
      transcript,
      content: transcript,
      title: details.title || document.title.replace(/ - YouTube$/, ''),
      url: `https://www.youtube.com/watch?v=${job.videoId}`,
      channelName: details.author || document.querySelector('#owner ytd-channel-name')?.textContent?.trim() || null,
      description: details.shortDescription || null,
      source,
      language: track?.languageCode || null,
      isAutoGenerated: track ? track.kind === 'asr' : null,
      segmentCount: segments.length,
      complete: true,
      extractionVersion: 2
    };
  }

  function visiblePanel() {
    return Array.from(document.querySelectorAll(PANEL_SELECTOR)).find(panel =>
      panel.getAttribute('visibility') !== 'ENGAGEMENT_PANEL_VISIBILITY_HIDDEN' &&
      !panel.hidden && panel.getBoundingClientRect().height > 0)?.closest('ytd-engagement-panel-section-list-renderer');
  }

  function transcriptControl() {
    // Dedicated transcript UI only. Never toggle CC or click an unrelated menu.
    return document.querySelector('ytd-video-description-transcript-section-renderer button') ||
      Array.from(document.querySelectorAll('button, ytd-menu-service-item-renderer')).find(element =>
        /^(show transcript|open transcript panel)$/i.test(
          (element.getAttribute('aria-label') || element.textContent || '').trim()));
  }

  async function panelFallback(job, player) {
    assertCurrent(job);
    const initialPanel = visiblePanel();
    const control = initialPanel ? null : transcriptControl();
    if (!initialPanel && !control) return null;
    const scroll = { x: root.scrollX, y: root.scrollY };
    let userInteracted = false;
    let panel = initialPanel;
    const onInteraction = event => { if (event.isTrusted) userInteracted = true; };
    root.addEventListener('pointerdown', onInteraction, true);
    root.addEventListener('keydown', onInteraction, true);
    root.addEventListener('wheel', onInteraction, true);
    try {
      control?.click();
      let previous = null;
      let stableSince = 0;
      const deadline = Date.now() + 6500;
      while (Date.now() < deadline) {
        assertCurrent(job);
        panel = visiblePanel();
        if (panel) {
          const data = await snapshot(job, true);
          const parsed = parser.parseTranscriptResponse(data?.panelData);
          const busy = Array.from(panel.querySelectorAll('[aria-busy="true"], tp-yt-paper-spinner[active]'))
            .some(element => element.getBoundingClientRect().height > 0);
          // Read the full backing segment list, not a potentially virtualized DOM
          // slice. Unknown/continued models fail closed rather than caching a prefix.
          if (parsed.complete && parsed.segments.length && !busy) {
            const signature = JSON.stringify(parsed.segments);
            if (signature !== previous) { previous = signature; stableSince = Date.now(); }
            else if (Date.now() - stableSince >= 500) {
              return result(job, player, parsed.segments, 'panel');
            }
          } else {
            previous = null;
          }
        }
        await delay(250, job);
      }
      throw failure('INCOMPLETE', 'Could not verify a complete YouTube transcript. Please try again after the panel finishes loading.');
    } finally {
      root.removeEventListener('pointerdown', onInteraction, true);
      root.removeEventListener('keydown', onInteraction, true);
      root.removeEventListener('wheel', onInteraction, true);
      // Do not undo the user's actions, close their existing panel, or manipulate
      // the next video's UI after navigation.
      if (!initialPanel && !userInteracted && currentVideoId() === job.videoId && !cleanedUp) {
        panel?.querySelector('button[aria-label="Close"], button[aria-label="Close transcript"], #visibility-button button')?.click();
        if (root.scrollX !== scroll.x || root.scrollY !== scroll.y) root.scrollTo(scroll.x, scroll.y);
      }
    }
  }

  async function extract(job) {
    const startedAt = performance.now();
    let data = null;
    try { data = await snapshot(job); } catch (_) { assertCurrent(job); }
    let player = data?.player;
    // Only fetch HTML when current player data is unavailable; no redundant
    // watch request alongside every successful caption download.
    if (!player) {
      try {
        player = parser.parsePlayerResponseFromHtml(
          await fetchText(`https://www.youtube.com/watch?v=${job.videoId}`, job), job.videoId);
      } catch (_) { assertCurrent(job); }
    }
    if (player?.videoDetails?.isLive ||
        player?.microformat?.playerMicroformatRenderer?.liveBroadcastDetails?.isLiveNow) {
      throw failure('LIVE', 'This video is live. A complete transcript is only available after it finishes processing.');
    }
    if (player?.playabilityStatus?.status && player.playabilityStatus.status !== 'OK') {
      throw failure('UNAVAILABLE', 'This YouTube video is not available in the current browser session.');
    }
    const tracks = player?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    const track = parser.selectTrack(tracks);
    let output = null;
    if (track) {
      try {
        const url = new URL(track.baseUrl);
        const captionUrl = url.searchParams.has('fmt') ? track.baseUrl :
          `${track.baseUrl}${url.search ? '&' : '?'}fmt=json3`;
        const segments = parser.parseCaptions(await fetchText(captionUrl, job));
        if (segments.length) output = result(job, player, segments, 'captions', track);
      } catch (_) { assertCurrent(job); }
    }
    if (!output && (data?.panelRequest || data?.transcriptParams) && data.context?.client?.clientVersion) {
      try {
        const endpoint = data.panelRequest ? 'get_panel' : 'get_transcript';
        const request = data.panelRequest || {
          params: data.transcriptParams, externalVideoId: job.videoId,
          languageCode: track?.languageCode, kind: track?.kind
        };
        const text = await fetchText(`https://www.youtube.com/youtubei/v1/${endpoint}?prettyPrint=false`, job, {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ context: data.context, ...request })
        });
        const parsed = parser.parseTranscriptResponse(JSON.parse(text));
        if (parsed.complete && parsed.segments.length) {
          output = result(job, player, parsed.segments, 'transcript', data.panelRequest ? null : track);
        }
      } catch (_) { assertCurrent(job); }
    }
    if (!output) output = await panelFallback(job, player);
    if (!output) {
      throw !player || tracks.length || data?.transcriptParams || data?.panelRequest
        ? failure('FETCH_FAILED', 'YouTube captions could not be retrieved. Please try again; captions may still be available on the page.')
        : failure('NO_CAPTIONS', 'No usable captions were found for this video. They may be unavailable or still processing.');
    }
    assertCurrent(job);
    console.debug('[Cindra] YouTube transcript extracted', JSON.stringify({
      videoId: output.videoId, source: output.source, segmentCount: output.segmentCount,
      language: output.language, isAutoGenerated: output.isAutoGenerated,
      availableTracks: tracks.map(item => ({ language: item.languageCode, kind: item.kind || 'manual' })),
      elapsedMs: Math.round(performance.now() - startedAt)
    }));
    return output;
  }

  function cancelActive() {
    active?.controller.abort(failure('NAVIGATED', 'The YouTube video changed. Please summarize the current video again.'));
  }

  function onNavigation() {
    if (active && currentVideoId() !== active.videoId) cancelActive();
  }

  function extractTranscriptOnce(videoId = currentVideoId()) {
    if (!videoId || currentVideoId() !== videoId) {
      return Promise.reject(failure('NAVIGATED', 'The YouTube video changed. Please summarize the current video again.'));
    }
    if (active?.videoId === videoId && !active.controller.signal.aborted) return active.promise;
    cancelActive();
    const job = { videoId, controller: new AbortController() };
    const timeout = setTimeout(() => job.controller.abort(
      failure('TIMEOUT', 'YouTube transcript extraction timed out. Please try again.')), 15000);
    const navigationCheck = setInterval(onNavigation, 100);
    active = job;
    job.promise = extract(job).finally(() => {
      clearTimeout(timeout);
      clearInterval(navigationCheck);
      if (active === job) active = null;
    });
    return job.promise;
  }

  function handleMessage(message, sender, sendResponse) {
    if (message?.action !== ACTIONS.EXTRACT_TRANSCRIPT) return false;
    const respond = messages.respondOnce(sendResponse);
    const validation = messages.validateMessage(message, [ACTIONS.EXTRACT_TRANSCRIPT]);
    if (!validation.ok || sender.id !== root.chrome.runtime.id) {
      respond({ success: false, error: validation.error || 'YouTube transcript request was not trusted.' });
      return false;
    }
    extractTranscriptOnce(message.videoId).then(respond).catch(error => {
      respond({ success: false, videoId: message.videoId, code: error.code || 'EXTRACTION_FAILED', error: error.message });
    });
    return true;
  }

  function onPageHide(event) {
    // A bfcache-restored page does not rerun content scripts; keep listeners alive.
    if (event.persisted) cancelActive();
    else cleanup();
  }

  function cleanup() {
    if (cleanedUp) return;
    cleanedUp = true;
    cancelActive();
    transcriptButton?.destroy();
    root.chrome.runtime.onMessage.removeListener(handleMessage);
    root.removeEventListener('yt-navigate-start', cancelActive);
    root.removeEventListener('yt-navigate-finish', onNavigation);
    root.removeEventListener('popstate', onNavigation);
    root.removeEventListener('pagehide', onPageHide);
  }

  root.chrome.runtime.onMessage.addListener(handleMessage);
  root.addEventListener('yt-navigate-start', cancelActive);
  root.addEventListener('yt-navigate-finish', onNavigation);
  root.addEventListener('popstate', onNavigation);
  root.addEventListener('pagehide', onPageHide);
  transcriptButton = new youtubeUi.YouTubeTranscriptButton({
    window: root, document: root.document,
    onCopy: async () => (await extractTranscriptOnce()).transcript,
    onError: error => errors.logError('Could not copy YouTube transcript', error)
  }).start();
  root.CindraYouTubeContent = { cleanup, extractTranscriptOnce };
})(globalThis);
