const { test, expect } = require('@playwright/test');
const { launchExtensionContext, extensionId } = require('./helpers.js');

const VIDEO_ID = 'cindra00001';
const URL = `https://www.youtube.com/watch?v=${VIDEO_ID}`;

function playerResponse(videoId = VIDEO_ID, tracks = [{ languageCode: 'en', kind: 'asr' }]) {
  return {
    videoDetails: { videoId, title: 'Transcript fixture', author: 'Fixture channel', lengthSeconds: '20' },
    playabilityStatus: { status: 'OK' },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: tracks.map(track => ({
      baseUrl: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${track.languageCode}`,
      ...track
    })) } }
  };
}

function fixtureHtml(response = playerResponse(), extra = '') {
  return `<!doctype html><html><head><title>Transcript fixture - YouTube</title></head><body>
    <div id="movie_player"></div><ytd-watch-flexy video-id="${VIDEO_ID}">
    <ytd-watch-metadata><div id="above-the-fold"><div id="top-row"><div id="subscribe-button"></div></div></div></ytd-watch-metadata>
    <button aria-label="Show transcript" onclick="window.panelClicks++">Show transcript</button>
    <button class="ytp-subtitles-button" onclick="window.ccClicks++">CC</button>
    </ytd-watch-flexy><script>
    window.panelClicks = 0; window.ccClicks = 0;
    window.fixturePlayer = ${JSON.stringify(response)};
    document.getElementById('movie_player').getPlayerResponse = () => window.fixturePlayer;
    document.getElementById('movie_player').getVideoData = () => ({ video_id: window.fixturePlayer?.videoDetails.videoId });
    </script>${extra}</body></html>`;
}

const captions = { events: [
  { tStartMs: 0, dDurationMs: 2000, segs: [{ utf8: 'First ' }, { utf8: 'sentence.' }] },
  { tStartMs: 5000, dDurationMs: 2000, segs: [{ utf8: 'I really really mean café & 日本語.' }] },
  { tStartMs: 18000, dDurationMs: 2000, segs: [{ utf8: 'Final sentence.' }] }
] };

async function extract(serviceWorker, videoId = VIDEO_ID) {
  return serviceWorker.evaluate(async ({ videoId }) => {
    const tabs = await chrome.tabs.query({ url: 'https://www.youtube.com/*' });
    return chrome.tabs.sendMessage(tabs[0].id, { action: 'extractTranscript', videoId });
  }, { videoId });
}

test('quiet auto captions use current MAIN-world player data without opening or scrolling the page', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    let watchRequests = 0;
    let captionRequests = 0;
    const page = await context.newPage();
    await page.route('https://www.youtube.com/**', route => {
      if (route.request().url().includes('/api/timedtext')) {
        captionRequests++;
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify(captions) });
      }
      watchRequests++;
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml() });
    });
    await page.goto(URL);
    const result = await extract(serviceWorker);
    expect(result, result.error).toMatchObject({ success: true, videoId: VIDEO_ID, complete: true, isAutoGenerated: true });
    expect(result.transcript).toBe('Transcript:\n\nFirst sentence.\n\nI really really mean café & 日本語.\n\nFinal sentence.');
    expect(await page.evaluate(() => [window.panelClicks, window.ccClicks, window.scrollY])).toEqual([0, 0, 0]);
    expect(watchRequests).toBe(1);
    expect(captionRequests).toBe(1);
  } finally {
    await context.close();
  }
});

function currentWatchScript(extra = '') {
  return `<script>
    const watch = document.querySelector('ytd-watch-flexy');
    watch.data = { currentVideoEndpoint: { watchEndpoint: { videoId: '${VIDEO_ID}' } } };
    window.ytcfg = { data_: { INNERTUBE_CONTEXT: { client: { clientName: 'WEB', clientVersion: 'test' } } } };
    ${extra}
  </script>`;
}

function modelSegments(count = 3) {
  return Array.from({ length: count }, (_, index) => ({ transcriptSegmentViewModel: {
    timestamp: `${Math.floor(index / 60)}:${String(index % 60).padStart(2, '0')}`,
    simpleText: `Segment ${index}.`
  } }));
}

test('empty captions fall through to the current transcript command without opening its panel', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    const requests = [];
    const page = await context.newPage();
    await page.route('https://www.youtube.com/**', route => {
      const url = route.request().url();
      requests.push(new globalThis.URL(url).pathname);
      if (url.includes('/api/timedtext')) return route.fulfill({ body: '' });
      if (url.includes('/youtubei/v1/get_panel')) {
        expect(route.request().postDataJSON()).toMatchObject({ panelId: 'current-transcript-panel', params: 'page-generated-params' });
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ contents: modelSegments(900) }) });
      }
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml(playerResponse(),
        '<ytd-video-description-transcript-section-renderer></ytd-video-description-transcript-section-renderer>' +
        currentWatchScript(`document.querySelector('ytd-video-description-transcript-section-renderer').data = {
          showEngagementPanelEndpoint: { identifier: { tag: 'current-transcript-panel' }, globalConfiguration: { params: 'page-generated-params' } }
        };`)) });
    });
    await page.goto(URL);
    const result = await extract(serviceWorker);
    expect(result, result.error).toMatchObject({ success: true, source: 'transcript', complete: true, segmentCount: 900 });
    expect(result.transcript.startsWith('Transcript:\n\nSegment 0.')).toBe(true);
    expect(result.transcript.endsWith('Segment 899.')).toBe(true);
    expect(result.transcript.match(/Segment \d+\./g)).toHaveLength(900);
    expect(requests).toEqual(['/watch', '/api/timedtext', '/youtubei/v1/get_panel']);
    expect(await page.evaluate(() => [window.panelClicks, window.ccClicks, window.scrollY])).toEqual([0, 0, 0]);
  } finally { await context.close(); }
});

test('legacy transcript requests carry the current video and automatic-caption track identity', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    const page = await context.newPage();
    await page.route('https://www.youtube.com/**', route => {
      const url = route.request().url();
      if (url.includes('/api/timedtext')) return route.fulfill({ body: '' });
      if (url.includes('/youtubei/v1/get_transcript')) {
        expect(route.request().postDataJSON()).toMatchObject({
          params: 'current-transcript', externalVideoId: VIDEO_ID, languageCode: 'en', kind: 'asr'
        });
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ contents: modelSegments() }) });
      }
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml(playerResponse(), currentWatchScript(
        `watch.data.command = { getTranscriptEndpoint: { params: 'current-transcript' } };`
      )) });
    });
    await page.goto(URL);
    expect(await extract(serviceWorker)).toMatchObject({ success: true, source: 'transcript', isAutoGenerated: true });
    expect(await page.evaluate(() => window.panelClicks)).toBe(0);
  } finally { await context.close(); }
});

for (const [alreadyOpen, slowCaptions] of [[false, false], [true, false], [false, true]]) {
  test(`panel fallback reads the full model and preserves UI (open: ${alreadyOpen}, slow: ${slowCaptions})`, async () => {
    const { context, serviceWorker } = await launchExtensionContext();
    try {
      const page = await context.newPage();
      const model = { videoId: VIDEO_ID, contents: modelSegments(800) };
      const extra = `<style>body { height: 2400px; } ytd-engagement-panel-section-list-renderer { display:block; height:200px; }
        [visibility="ENGAGEMENT_PANEL_VISIBILITY_HIDDEN"] { display:none; }</style>
        <ytd-engagement-panel-section-list-renderer target-id="engagement-panel-searchable-transcript"
          visibility="ENGAGEMENT_PANEL_VISIBILITY_${alreadyOpen ? 'EXPANDED' : 'HIDDEN'}">
          <button aria-label="Close transcript">Close</button><div>Only one visible DOM segment.</div>
        </ytd-engagement-panel-section-list-renderer>` + currentWatchScript(`
          const panel = document.querySelector('ytd-engagement-panel-section-list-renderer');
          panel.data = ${JSON.stringify(model)};
          window.closeClicks = 0;
          panel.querySelector('button').onclick = () => { window.closeClicks++; panel.setAttribute('visibility', 'ENGAGEMENT_PANEL_VISIBILITY_HIDDEN'); };
          document.querySelector('[aria-label="Show transcript"]').onclick = () => {
            window.panelClicks++; panel.setAttribute('visibility', 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED');
          };`);
      let releaseCaption;
      await page.route('https://www.youtube.com/**', async route => {
        if (route.request().url().includes('/api/timedtext')) {
          if (slowCaptions) await new Promise(resolve => { releaseCaption = resolve; });
          return route.fulfill({ status: slowCaptions ? 200 : 403, body: JSON.stringify(captions) }).catch(() => {});
        }
        return route.fulfill({ contentType: 'text/html', body: fixtureHtml(playerResponse(), extra) });
      });
      await page.goto(URL);
      await page.evaluate(() => window.scrollTo(0, 300));
      const result = await extract(serviceWorker);
      expect(result, result.error).toMatchObject({ success: true, source: 'panel', segmentCount: 800, complete: true });
      releaseCaption?.();
      expect(result.transcript.endsWith('Segment 799.')).toBe(true);
      expect(result.transcript).not.toContain('Only one visible');
      expect(await page.evaluate(() => [window.panelClicks, window.closeClicks, window.ccClicks, window.scrollY]))
        .toEqual([alreadyOpen ? 0 : 1, alreadyOpen ? 0 : 1, 0, 300]);
    } finally { await context.close(); }
  });
}

test('pending requests are shared per video and cancelled on SPA navigation', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    let requests = 0;
    let release;
    let started;
    const pending = new Promise(resolve => { started = resolve; });
    const page = await context.newPage();
    await page.route('https://www.youtube.com/**', async route => {
      if (route.request().url().includes('/api/timedtext')) {
        requests++;
        if (requests === 1) { started(); await new Promise(resolve => { release = resolve; }); }
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify(captions) }).catch(() => {});
      }
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml() });
    });
    await page.goto(URL);
    const first = extract(serviceWorker);
    const second = extract(serviceWorker);
    await pending;
    const nextId = 'cindra00002';
    await page.evaluate(({ nextId, player }) => {
      history.pushState({}, '', `/watch?v=${nextId}`);
      window.fixturePlayer = player;
      window.dispatchEvent(new Event('yt-navigate-finish'));
    }, { nextId, player: playerResponse(nextId) });
    release();
    for (const response of await Promise.all([first, second])) {
      expect(response).toMatchObject({ success: false, code: 'NAVIGATED' });
      expect(response.transcript).toBeUndefined();
    }
    expect(requests).toBe(1);
    const result = await extract(serviceWorker, nextId);
    expect(result).toMatchObject({ success: true, videoId: nextId, complete: true });
    expect(requests).toBe(2);
    expect(await page.evaluate(() => window.panelClicks)).toBe(0);
  } finally { await context.close(); }
});

test('a panel with an unresolved continuation never returns a partial transcript', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    const page = await context.newPage();
    const extra = `<ytd-engagement-panel-section-list-renderer target-id="engagement-panel-searchable-transcript"
      style="display:block;height:200px"><div>A visible prefix is not a full transcript.</div>
      </ytd-engagement-panel-section-list-renderer>` + currentWatchScript(`
        document.querySelector('ytd-engagement-panel-section-list-renderer').data = {
          videoId: '${VIDEO_ID}', contents: ${JSON.stringify(modelSegments())},
          continuations: [{ nextContinuationData: { continuation: 'more-cues' } }]
        };`);
    await page.route('https://www.youtube.com/**', route => route.request().url().includes('/api/timedtext')
      ? route.fulfill({ body: '' })
      : route.fulfill({ contentType: 'text/html', body: fixtureHtml(playerResponse(), extra) }));
    await page.goto(URL);
    const result = await extract(serviceWorker);
    expect(result).toMatchObject({ success: false, code: 'INCOMPLETE' });
    expect(result.transcript).toBeUndefined();
  } finally { await context.close(); }
});

test('the MAIN-world bridge rejects requests without a trusted YouTube top-level document', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    const page = await context.newPage();
    await page.goto(`chrome-extension://${extensionId(serviceWorker)}/ui/popup/popup.html`);
    const response = await page.evaluate(() => chrome.runtime.sendMessage({
      action: 'readYouTubePage', videoId: 'cindra00001'
    }));
    expect(response.success).toBe(false);
    expect(response.error).toContain('not trusted');
  } finally { await context.close(); }
});

test('manual tracks use metadata, and XML preserves entities, non-English text, and the final cue', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    const requested = [];
    const page = await context.newPage();
    const tracks = [
      { languageCode: 'fr', kind: 'asr', baseUrl: `https://www.youtube.com/api/timedtext?v=${VIDEO_ID}&track=fr` },
      { languageCode: 'en', kind: 'asr', baseUrl: `https://www.youtube.com/api/timedtext?v=${VIDEO_ID}&track=auto` },
      { languageCode: 'en', baseUrl: `https://www.youtube.com/api/timedtext?v=${VIDEO_ID}&track=manual&fmt=srv3` }
    ];
    await page.route('https://www.youtube.com/**', route => {
      if (route.request().url().includes('/api/timedtext')) {
        requested.push(route.request().url());
        return route.fulfill({ contentType: 'text/xml', body: '<timedtext><body><p t="0" d="2000">Café &amp; <s>日本語.</s></p><p t="18000" d="2000">Final cue.</p></body></timedtext>' });
      }
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml(playerResponse(VIDEO_ID, tracks)) });
    });
    await page.goto(URL);
    const result = await extract(serviceWorker);
    expect(result).toMatchObject({ success: true, language: 'en', isAutoGenerated: false, segmentCount: 2 });
    expect(result.transcript).toBe('Transcript:\n\nCafé & 日本語.\n\nFinal cue.');
    expect(requested).toEqual([tracks[2].baseUrl]);
  } finally { await context.close(); }
});

for (const code of ['NO_CAPTIONS', 'LIVE', 'UNAVAILABLE']) {
  test(`${code} is an honest failure, not a transcript or UI toggle`, async () => {
    const { context, serviceWorker } = await launchExtensionContext();
    try {
      const response = playerResponse(VIDEO_ID, []);
      if (code === 'LIVE') response.videoDetails.isLive = true;
      if (code === 'UNAVAILABLE') response.playabilityStatus.status = 'LOGIN_REQUIRED';
      const page = await context.newPage();
      await page.route('https://www.youtube.com/**', route => route.fulfill({
        contentType: 'text/html', body: fixtureHtml(response).replace(/<button[\s\S]*?<\/button>/g, '')
      }));
      await page.goto(URL);
      const result = await extract(serviceWorker);
      expect(result).toMatchObject({ success: false, videoId: VIDEO_ID, code });
      expect(result.transcript).toBeUndefined();
      expect(await page.evaluate(() => [window.panelClicks, window.ccClicks])).toEqual([0, 0]);
    } finally { await context.close(); }
  });
}

test('an absent player does not beat a successful fresh watch-page caption retrieval', async () => {
  const { context, serviceWorker } = await launchExtensionContext();
  try {
    let watchRequests = 0;
    const page = await context.newPage();
    await page.route('https://www.youtube.com/**', async route => {
      if (route.request().url().includes('/api/timedtext')) {
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify(captions) });
      }
      watchRequests++;
      if (watchRequests > 1) {
        await new Promise(resolve => setTimeout(resolve, 100));
        return route.fulfill({ contentType: 'text/html', body: `<script>var ytInitialPlayerResponse = ${JSON.stringify(playerResponse())};</script>` });
      }
      return route.fulfill({ contentType: 'text/html', body: fixtureHtml(null).replace(/<button[\s\S]*?<\/button>/g, '') });
    });
    await page.goto(URL);
    const result = await extract(serviceWorker);
    expect(result, result.error).toMatchObject({ success: true, videoId: VIDEO_ID, complete: true });
    expect(result.transcript).toContain('Final sentence.');
    expect(watchRequests).toBe(2);
  } finally {
    await context.close();
  }
});
